#!/bin/bash

ARCHIVE=none
VENDOR=none

if [ -f vbnt-k_ti_16.3.7498_4_20171129.tar.gz ]; then
    ARCHIVE=vbnt-k_ti_16.3.7498_4_20171129
    VENDOR=ti
elif [ -f vant-w_fastweb_16.2.7384_1_20170925.tar.gz ]; then
    ARCHIVE=vant-w_fastweb_16.2.7384_1_20170925
    VENDOR=fw
fi

if [ "$ARCHIVE" = "none" ]; then
    echo "Unable to find archive vbnt-k_ti_16.3.7498_4_20171129.tar.gz or vant-w_fastweb_16.2.7384_1_20170925.tar.gz."
    echo "Operation completed unsuccesfully."
else
    tar xzvf $ARCHIVE.tar.gz -C dl
    mv dl/$ARCHIVE/$ARCHIVE.tar.bz2 dl
    rm -r dl/$ARCHIVE

    tar jxvf dl/$ARCHIVE.tar.bz2 -C dl
    rm dl/$ARCHIVE.tar.bz2

    ##################
    # PREPARE EXTERN #
    ##################

    rm -rf extern
    cp -r extern.ori extern
    mv extern/broadcom-bsp/bcmdrivers/opensource.$VENDOR extern/broadcom-bsp/bcmdrivers/opensource
    mv extern/broadcom-bsp/shared/opensource.$VENDOR extern/broadcom-bsp/shared/opensource
    rm -rf extern/broadcom-bsp/bcmdrivers/opensource.*
    rm -rf extern/broadcom-bsp/shared/opensource.*

    mkdir -p extern/broadcom-bsp/shared/opensource/boardparms/bcm963xx/
    mkdir -p extern/broadcom-bsp/shared/opensource/spi/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/pmc/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/drv/unimac/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/drv/mdio/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/drv/phys/extphy/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/drv/phys/egphy/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/drv/dpi/
    mkdir -p extern/broadcom-bsp/shared/opensource/include/rdp/base/
    mkdir -p extern/broadcom-bsp/shared/opensource/pmc/impl2/
    mkdir -p extern/broadcom-bsp/shared/opensource/pmc/impl1/
    mkdir -p extern/broadcom-bsp/shared/opensource/drv/unimac/
    mkdir -p extern/broadcom-bsp/shared/opensource/drv/mdio/
    mkdir -p extern/broadcom-bsp/shared/opensource/drv/phys/extphy/
    mkdir -p extern/broadcom-bsp/shared/opensource/drv/phys/egphy/
    mkdir -p extern/broadcom-bsp/shared/opensource/drv/dpi/
    mkdir -p extern/broadcom-bsp/shared/opensource/flash/
    mkdir -p extern/broadcom-bsp/shared/opensource/rdp/
    mkdir -p extern/broadcom-bsp/shared/opensource/utils/
    mkdir -p extern/broadcom-bsp/shared/opensource/drivers/

    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/bridge/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/wfd/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl3/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl4/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/timer/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/busses/impl2/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/busses/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/chips/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/pcmshim/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/dectshim/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/bdmf/impl1/userspace/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/bdmf/impl1/framework/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/moca/impl2/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/dpi/impl1/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/
    mkdir -p extern/broadcom-bsp/bcmdrivers/opensource/char/i2s/impl1/

    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/boardparms/bcm963xx/boardparms_voice.c extern/broadcom-bsp/shared/opensource/boardparms/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/boardparms/bcm963xx/boardparms.c extern/broadcom-bsp/shared/opensource/boardparms/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/boardparms/bcm963xx/bp_defs.h extern/broadcom-bsp/shared/opensource/boardparms/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/spi/bcmHsSpi.c extern/broadcom-bsp/shared/opensource/spi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/spi/bcmSpiRes.c extern/broadcom-bsp/shared/opensource/spi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcmTag.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/robosw_reg.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63138_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/robosw_reg_shared.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6368_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcmnetlink.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcm_misc_hw_init.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/boardparms.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6818_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/60333_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6318_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6328_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63148_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6318_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6318_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/boardparms_voice.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63138_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/flash_api.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/60333_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63381_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcm_mm.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6838_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6828_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63138_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcm_ethsw.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6362_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63148_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcm_hwdefs.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63381_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6838_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/bcm_chip_arch.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63268_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63381_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/60333_intr.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6838_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/6818_map_part.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/bcm963xx/63148_cpu.h extern/broadcom-bsp/shared/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_apm.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_drv.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/BPCM.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/command.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_usb.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_sata.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_sar.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_dsl.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/clk_rst.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_pcie.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_pcm.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_switch.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/pmc/pmc_cpu_core.h extern/broadcom-bsp/shared/opensource/include/pmc/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/unimac/unimac_drv.h extern/broadcom-bsp/shared/opensource/include/drv/unimac/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/mdio/mdio_drv.h extern/broadcom-bsp/shared/opensource/include/drv/mdio/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/phys/extphy/extphy_drv.h extern/broadcom-bsp/shared/opensource/include/drv/phys/extphy/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/phys/egphy/egphy_drv.h extern/broadcom-bsp/shared/opensource/include/drv/phys/egphy/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/phys/phys_common_drv.h extern/broadcom-bsp/shared/opensource/include/drv/phys/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/dpi/data_path_init.h extern/broadcom-bsp/shared/opensource/include/drv/dpi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/dpi/oren_data_path_init.h extern/broadcom-bsp/shared/opensource/include/drv/dpi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/drv/dpi/bcm63138_data_path_init.h extern/broadcom-bsp/shared/opensource/include/drv/dpi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_eth.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_ubus.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/96838_rdp_map.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_psram.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_drv_bbh.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_subsystem_common.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_gponclkout_cfg.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/base/packing.h extern/broadcom-bsp/shared/opensource/include/rdp/base/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_ms1588.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_map.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_cpu_ring_sim.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_ih.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/access_macros.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_runner.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_cpu_ring_inline.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_bpm.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/bl_os_wraper.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_bbh.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_gpon.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_drv_sbpm.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/hwapi_mac.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_drv_ih.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_dma.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_drv_bpm.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/963148_rdp_map.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_cpu_ring.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/963138_rdp_map.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_wan.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_sbpm.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/include/rdp/rdp_mm.h extern/broadcom-bsp/shared/opensource/include/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/Makefile extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/pmc_sysfs.c extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/pmc_pcie.c extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/command.h extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/pmcapp.h extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/pmc_drv.c extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl2/clk_rst.c extern/broadcom-bsp/shared/opensource/pmc/impl2/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/Makefile extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_sysfs.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/app63381.h extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_dsl.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_pcie.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/restart.h extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_apm.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmcapp.h extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_drv.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_sar.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/restart_a42.h extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_pcm.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_usb.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/clk_rst.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_switch.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_sata.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/pmc/impl1/pmc_cpu_core.c extern/broadcom-bsp/shared/opensource/pmc/impl1/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/unimac/unimac_drv_impl1.c extern/broadcom-bsp/shared/opensource/drv/unimac/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/mdio/mdio_drv_impl1.c extern/broadcom-bsp/shared/opensource/drv/mdio/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/phys/phys_common_drv.c extern/broadcom-bsp/shared/opensource/drv/phys/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/phys/extphy/extphy_drv_impl1.c extern/broadcom-bsp/shared/opensource/drv/phys/extphy/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/phys/egphy/egphy_drv_impl1.c extern/broadcom-bsp/shared/opensource/drv/phys/egphy/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/dpi/oren_data_path_init.c extern/broadcom-bsp/shared/opensource/drv/dpi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drv/dpi/bcm63138_data_path_init.c extern/broadcom-bsp/shared/opensource/drv/dpi/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/spinandflash.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/cfiflash.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/flash_api.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/nandflash.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/flash_common.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/flash/spiflash.c extern/broadcom-bsp/shared/opensource/flash/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/Makefile extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_drv_sbpm.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_bbh_arrays.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_drv_ih.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_cpu_ring.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_dma_arrays.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_drv_bbh.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_runner_arrays.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_drv_bpm.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/rdp/rdp_ubus_arrays.c extern/broadcom-bsp/shared/opensource/rdp/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/utils/shared_utils.c extern/broadcom-bsp/shared/opensource/utils/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_misc_hw_init_impl2.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_pinmux_impl2.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_chip_arch.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_led_impl3.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_gpio_impl2.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_ethsw_impl1.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_misc_hw_init_impl1.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_led_impl2.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_misc_hw_init_impl4.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_ethsw_impl2.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_pinmux_impl1.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_gpio_impl1.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_misc_hw_init_impl3.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/wan_drv_impl1.c extern/broadcom-bsp/shared/opensource/drivers/
    cp dl/$ARCHIVE/bcm_userspace/broadcom_apps/shared/opensource/drivers/bcm_led_impl1.c extern/broadcom-bsp/shared/opensource/drivers/

    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/lib/pktdma/impl1/bcmPktDmaXtmDqm.c extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/lib/pktdma/impl1/bcmPktDma.c extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/lib/pktdma/impl1/bcmPktDmaXtmIudma.c extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/lib/pktdma/impl1/bcmPktDmaBds.c extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/lib/pktdma/impl1/bcmPktDmaEthDqm.c extern/broadcom-bsp/bcmdrivers/opensource/net/lib/pktdma/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/bridge/impl1/Makefile extern/broadcom-bsp/bcmdrivers/opensource/net/bridge/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/bridge/impl1/br_fp.c extern/broadcom-bsp/bcmdrivers/opensource/net/bridge/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/wfd/impl1/Makefile extern/broadcom-bsp/bcmdrivers/opensource/net/wfd/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/wfd/impl1/wfd_dev.c extern/broadcom-bsp/bcmdrivers/opensource/net/wfd/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl3/bcmxtmrtimpl.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl3/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl3/bcmxtmrtbond.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl3/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl3/bcmxtmrt.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl3/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl4/bcmxtmrtimpl.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl4/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl4/bcmxtmrtbond.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl4/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl4/bcmxtmrtbond.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl4/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl4/bcmxtmrt.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl4/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_iq.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/bcmxtmrtimpl.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/bcmxtmrtbond.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_bpm.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/bcmxtmrtbond.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_runner.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/bcmxtmrt.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_iq.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_runner.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_bpm.h extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/xtmrt/impl5/xtmrt_cfg.c extern/broadcom-bsp/bcmdrivers/opensource/net/xtmrt/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmeth_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcm_eth.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmenet_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmenet.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmmii.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcm_eth.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmenet_dma_inline_impl6.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl6/bcmeth_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl6/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_ethtool.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_dma_inline.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_common.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmswaccess_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmswshared.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmswaccess_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmswaccess.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_runner_inline.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_ethtool.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_runner.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmswaccess.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/shared/bcmenet_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/shared/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/eth_pwrmngt.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmmii_xtn.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmenet_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_runner.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_phy.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmenet_runner.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_phy_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmenet.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmgmac.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_runner.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmmii.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmenet_shared_src.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw_runner.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw_dma.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw_runner.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/ethsw_phy_runner.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmsw_dma.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/bcmswdefs.h extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/net/enet/impl5/eth_pwrmngt.c extern/broadcom-bsp/bcmdrivers/opensource/net/enet/impl5/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/skb_defines.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/wfd_dev.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pktCmf_6816_public.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/rdpa_drv.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_map_part.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_cpu.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmpwrmngtcfg.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/fap.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm/bcmswapitypes.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/bcm/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm/bcmswapistat.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/bcm/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_vlan_defs.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmnet.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pmd.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/chipinfo_ioctl.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmpci.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/wan_drv.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/spidevices.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/simio_def_common.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_OS_Deps.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmxtmrt.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_tm_defs.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pcmshimdrv.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmPktDmaHooks.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/runner_wfd_inline.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/portMirror.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/laser.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pktCmf_6368_public.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmxtmcfg.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/gpon_i2c.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/BcmMirror.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bmoca.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm_intr.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/simio_user_kernel.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmHwAcc.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcm3450.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/otp_ioctl.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmgmac.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pktCmf_public.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/pktHdr.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmPktDma.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/bcmgmacctl.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/include/bcm963xx/dectshimdrv.h extern/broadcom-bsp/bcmdrivers/opensource/include/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/timer/impl1/bcm963xx_timer.c extern/broadcom-bsp/bcmdrivers/opensource/char/timer/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/Makefile extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_drv.c extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_blog_parse.c extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_vlan.c extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_blog_parse.h extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_vlan.h extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/rdpa_mw/impl1/rdpa_mw_sys_init.c extern/broadcom-bsp/bcmdrivers/opensource/char/rdpa_mw/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/brcm_rdb_util.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_drv.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/chal_types.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_atr.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_user.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_board.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/chal_simio.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_atr.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_user_kernel.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_api.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/brcm_rdb_simi.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/simio_board.c extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/chal_simio.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/sim_card/impl1/sim_export_defs.h extern/broadcom-bsp/bcmdrivers/opensource/char/sim_card/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/busses/impl2/i2c_bcm6xxx.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/busses/impl2/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/busses/impl1/i2c_bcm6xxx.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/busses/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/chips/impl1/gpon_i2c.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/chips/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/chips/impl1/sfp_i2c.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/chips/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/chips/impl1/laser_i2c.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/chips/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2c/chips/impl1/bcm3450.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2c/chips/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/pcmshim/impl1/pcmshim.c extern/broadcom-bsp/bcmdrivers/opensource/char/pcmshim/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/dectshim/impl1/dect_shim.c extern/broadcom-bsp/bcmdrivers/opensource/char/dectshim/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/dectshim/impl1/dectshimdrv.c extern/broadcom-bsp/bcmdrivers/opensource/char/dectshim/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/bdmf/impl1/userspace/bdmf_shell_client.c extern/broadcom-bsp/bcmdrivers/opensource/char/bdmf/impl1/userspace/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/bdmf/impl1/framework/bdmf_codegen.c extern/broadcom-bsp/bcmdrivers/opensource/char/bdmf/impl1/framework/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_des3_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/sputest.c extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_aes_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_des3_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_aes_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_aes_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_aes_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_des_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_des3_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_des3_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_des_md5_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_rx_des_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/spudd/impl2/test/spudrv_tx_des_sha1_data.h extern/broadcom-bsp/bcmdrivers/opensource/char/spudd/impl2/test/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/moca/impl2/bmoca-6802.c extern/broadcom-bsp/bcmdrivers/opensource/char/moca/impl2/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/moca/impl2/bmoca-6816.c extern/broadcom-bsp/bcmdrivers/opensource/char/moca/impl2/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/dpi/impl1/dpi.c extern/broadcom-bsp/bcmdrivers/opensource/char/dpi/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/bcm63xx_flash.c extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/spidevices.c extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/bcm63xx_led.c extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/bbsi.h extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/bbsiExecSeq.h extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/bbsi.c extern/broadcom-bsp/bcmdrivers/opensource/char/board/bcm963xx/impl1/bbsi/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2s/impl1/i2s.h extern/broadcom-bsp/bcmdrivers/opensource/char/i2s/impl1/
    cp dl/$ARCHIVE/kernel/broadcom_modules/bcmdrivers/opensource/char/i2s/impl1/i2s.c extern/broadcom-bsp/bcmdrivers/opensource/char/i2s/impl1/

    cd extern
    patch -p1 < ../extern.patch
    cd ..

    ##################
    # PREPARE KERNEL #
    ##################

    rm -rf dl/linux-3.4.11
    cp dl/linux-3.4.11.tar.xz.$VENDOR dl/linux-3.4.11.tar.xz
    tar xJvf dl/linux-3.4.11.tar.xz -C dl

    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/vlanctl_bind.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/blog_rule.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/dpistats.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/flwstif.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/blog.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/urlinfo.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/devinfo.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/gbpm.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/core/iqos.c dl/linux-3.4.11/net/core/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_igmp.c dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_mld.c dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_mld.h dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_mcast.c dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_igmp.h dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_flows.c dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_mcast.h dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/netfilter/ebt_skiplog.c dl/linux-3.4.11/net/bridge/netfilter/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_flows.h dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/bridge/br_netlink_mcpd.c dl/linux-3.4.11/net/bridge/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/ipv4/netfilter/nf_nat_rtsp.c dl/linux-3.4.11/net/ipv4/netfilter/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/ipv4/netfilter/nf_nat_pt.c dl/linux-3.4.11/net/ipv4/netfilter/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/net/netfilter/xt_SKIPLOG.c dl/linux-3.4.11/net/netfilter/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/kernel/bcm_log.c dl/linux-3.4.11/kernel/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/gbpm.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/iqos.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/brcm_dll.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/blog_net.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/blog_rule.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/bcm_skb_defines.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/vlanctl_bind.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/bcm_log.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/mtd/bchp_nand_7x.h dl/linux-3.4.11/include/linux/mtd/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/mtd/mtd64.h dl/linux-3.4.11/include/linux/mtd/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/nbuff.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/flwstif.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/netfilter/nf_conntrack_rtsp.h dl/linux-3.4.11/include/linux/netfilter/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/bcm_log_mod.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/bcm_realtime.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/include/linux/blog.h dl/linux-3.4.11/include/linux/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/fs/proc/proc_brcm.c dl/linux-3.4.11/fs/proc/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/irq.c dl/linux-3.4.11/arch/arm/mach-bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/timex.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/irqs.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/barriers.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/memory.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/clkdev.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/uncompress.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/vmalloc.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/hardware.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/system.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/debug-macro.S dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/smp.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/include/mach/io.h dl/linux-3.4.11/arch/arm/mach-bcm963xx/include/mach/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/mach-bcm963xx/prom.c dl/linux-3.4.11/arch/arm/mach-bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/clock.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/b15_core.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/ca9mp_cache.S dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_sata.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/pcie-msi-bcm63xx.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_cpufreq.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/bsp.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/bcm63xx_acp.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/ca9mpcore.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/bcm63xx_timer.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/bcm63xx_pcie.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/clock.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/include/plat/b15core.h dl/linux-3.4.11/arch/arm/plat-bcm63xx/include/plat/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_timer.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/pcie-bcm63xx.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_pcie.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63138.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/cache-l310.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_usb.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/ca9mp_timer.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/platsmp.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63148.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/plat-ca9mp-headsmp.S dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/ca9mp_core.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/arm/plat-bcm63xx/bcm63xx_acp.c dl/linux-3.4.11/arch/arm/plat-bcm63xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/irq.c dl/linux-3.4.11/arch/mips/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/pwrmngtclk.c dl/linux-3.4.11/arch/mips/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/smp-brcm.c dl/linux-3.4.11/arch/mips/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/prom.c dl/linux-3.4.11/arch/mips/bcm963xx/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/ktools/bounce.c dl/linux-3.4.11/arch/mips/bcm963xx/ktools/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/bcm963xx/ktools/pmontool.c dl/linux-3.4.11/arch/mips/bcm963xx/ktools/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/kernel/csrc-r4k-bcm-pwr.c dl/linux-3.4.11/arch/mips/kernel/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/kernel/cevt-r4k-bcm-pwr.c dl/linux-3.4.11/arch/mips/kernel/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/include/asm/bounce.h dl/linux-3.4.11/arch/mips/include/asm/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/arch/mips/include/asm/pmonapi.h dl/linux-3.4.11/arch/mips/include/asm/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/drivers/mtd/nand/bcm63xx_spinand.c dl/linux-3.4.11/drivers/mtd/nand/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/drivers/mtd/brcmnand/brcmnand_cet.c dl/linux-3.4.11/drivers/mtd/brcmnand/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/drivers/mtd/brcmnand/bcm63xx-nand.c dl/linux-3.4.11/drivers/mtd/brcmnand/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/drivers/mtd/brcmnand/brcmnand_bbt.c dl/linux-3.4.11/drivers/mtd/brcmnand/
    cp dl/$ARCHIVE/kernel/broadcom_kernel/kernel/linux-3.4rt/drivers/mtd/maps/bcm963xx.c dl/linux-3.4.11/drivers/mtd/maps/

    rm dl/linux-3.4.11.tar.xz
    cd dl
    tar cJvf linux-3.4.11.tar.xz linux-3.4.11
    cd ..
    rm -r dl/linux-3.4.11
    rm -r dl/$ARCHIVE
fi
