#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1
NAME=questd

start_service() {
	procd_open_instance
	procd_set_param command "/sbin/questd"
	procd_set_param respawn
	procd_close_instance
}

stop() {
	#stop_service() is called after procd killed the service
	echo ;
}

service_triggers()
{
	procd_add_reload_trigger network wireless
}

reload_service() {
	ubus -t 5 call router.network reload
}
